### ISSUE TITLE
es6+

### ISSUE THREAD

**Issue by calebboyd** [bestander/deploy-azure-cdn#6]
I was experiencing some errors using this on windows and also when directories were included in the globbing pattern. As a result and as an experiment I ended up [implementing] this tool in ES6/7. Let me know if you're interested and I can submit a PR.

[implementing]: https://github.com/telepharm/azure-cdn/blob/master/index.src.js

**Comment by bestander** [comment]
I love ES6/7, so a PR is welcome.
As long as API is not broken and unit tests are working.

**Comment by calebboyd** [comment]
Jest seems to be all sorts of broken anything but the oldest node versions... :/

**Comment by bestander** [comment]
Yep,  quite frustrating
